package lk.ijse.project_dkf.util;
public enum Rout {
    LOGIN ,NEW_AC, DASHBOARD, USER_SETTINGS, ORDER, BUYER, NEW_ORDER, OUTPUT, PAKING, CUT_IN, MATERIAL_IN ,
    ORDER_RATIO, TRIM_CARD, MAIN_DASHBOARD, SHIP , PASSWORD ,GMAIL, FORGOT_PASS, PASSWORD_SETTING
}